import { Button, VerticalBox, ListView } from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property <string> selectedUser: "";
    in-out property <[string]> userList: []; // Property to hold the list of users
    callback request-login(string);

    VerticalBox {
        // List of users
        ListView {
            for user in root.userList : Button {
                text: user;

                clicked => {
                    root.request-login(user);
                }
            }
        }
    }
}
